### ISSUE TITLE
failed to put mappings on indices [[test]], type [test]

### ISSUE THREAD

**Issue by anbu992003** [kzwang/elasticsearch-image#3]
curl -XPUT 'localhost:9200/test/test/_mapping' -d '{

> ```
> "test": {
>     "properties": {
>         "my_img": {
>             "type": "image",
>             "feature": {
>                 "CEDD": {
>                     "hash": "BIT_SAMPLING"
>                 },
>                 "JCD": {
>                     "hash": ["BIT_SAMPLING", "LSH"]
>                 },
>                 "FCTH": {}
>             },
>             "metadata": {
>                 "jpeg.image_width": {
>                     "type": "string",
>                     "store": "yes"
>                 },
>                 "jpeg.image_height": {
>                     "type": "string",
>                     "store": "yes"
>                 }
>             }
>         }
>     }
> }
> ```
> 
> }'

[2014-07-14 18:16:16,641][DEBUG][action.admin.indices.mapping.put] [Ikthalon] failed to put mappings on indices [[test]], type [test]
org.elasticsearch.index.mapper.MapperParsingException: No handler for type [image] declared on field [my_img]
        at org.elasticsearch.index.mapper.object.ObjectMapper$TypeParser.parseProperties(ObjectMapper.java:256)
        at org.elasticsearch.index.mapper.object.ObjectMapper$TypeParser.parse(ObjectMapper.java:216)
        at org.elasticsearch.index.mapper.DocumentMapperParser.parse(DocumentMapperParser.java:203)
        at org.elasticsearch.index.mapper.DocumentMapperParser.parseCompressed(DocumentMapperParser.java:185)
        at org.elasticsearch.index.mapper.MapperService.parse(MapperService.java:387)
        at org.elasticsearch.index.mapper.MapperService.parse(MapperService.java:377)
        at org.elasticsearch.cluster.metadata.MetaDataMappingService$5.execute(MetaDataMappingService.java:540)
        at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:308)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:134)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
        at java.lang.Thread.run(Thread.java:722)
{"error":"MapperParsingException[No handler for type [image] declared on field [my_img]]","status":400}

**Comment by kadishmal** [comment]
Have you restarted the ElasticSearch after installing this plugin?

**Comment by bhardwajD** [comment]
what is the alternative way to image indexing and searching in ES 2.4, as elasticsearch-image is not working on the same.

Thanks in advance for the help

**Comment by kadishmal** [comment]
I suggest going with machine learning. There are many open source tools nowadays which didn't exist couple years ago. You can start from:
- Free and open source face recognition with deep neural networks. https://cmusatyalab.github.io/openface/
  
  This library is very extensive. Has some serious work put in it. It has Docker images to get started in minutes, has many demos/examples. Since it is for face recognition, it also covers face/object detection, indexing (actually learning via a neural network), and finally searching (again through the neural network).
- https://medium.com/@ageitgey/machine-learning-is-fun-part-4-modern-face-recognition-with-deep-learning-c3cffc121d78#.201ic8z89
  
  This is an amazing tutorial with up to date instructions.
- http://torch.ch
- http://karpathy.github.io/neuralnets/
  
  Andrej Karpathy's personal blog. This guys is crazy. He explains Neural Networks as if it is just a game.

I hope this will help you get started.
