### ISSUE TITLE
NullPointerException  in AbstractImageScorer

### ISSUE THREAD

**Issue by such** [kzwang/elasticsearch-image#5]
Hello,

I'm using ES 3.2 and elasticsearch-image-1.3.0-SNAPSHOT.

I have the following error when I try to execute my request:

```
[2014-09-09 15:45:06,137][DEBUG][action.search.type       ] [Vanisher] [development_leak_items][3], node[j6322b2GSHiBq9Ks4HyWLA], [P], s[STARTED]: Failed to execute [org.elasticsearch.action.search.SearchRequest@500994df] lastShard [true].search.query.QueryPhaseExecutionException: [development_leak_items][3]: query[filtered(cover_image.FCTH,FCTH)->cache(_type:leak_item)],from[0],size[10]: Query Failed [Failed to execute main query]
        at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:162)
        at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:261)
        at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:206)
        at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:203)
        at org.elasticsearch.search.action.SearchServiceTransportAction$23.run(SearchServiceTransportAction.java:517)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.elasticsearch.ElasticsearchImageProcessException: Failed to calculate score
        at org.elasticsearch.index.query.image.AbstractImageScorer.score(AbstractImageScorer.java:57)
        at org.apache.lucene.search.TopScoreDocCollector$OutOfOrderTopScoreDocCollector.collect(TopScoreDocCollector.java:140)
        at org.apache.lucene.search.Weight$DefaultBulkScorer.scoreAll(Weight.java:193)
        at org.apache.lucene.search.Weight$DefaultBulkScorer.score(Weight.java:163)
        at org.apache.lucene.search.BulkScorer.score(BulkScorer.java:35)
        at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:621)
        at org.elasticsearch.search.internal.ContextIndexSearcher.search(ContextIndexSearcher.java:175)
        at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:491)
        at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:448)
        at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:281)
        at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:269)
        at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:156)
        ... 7 more
Caused by: java.lang.NullPointerException
        at org.elasticsearch.index.query.image.AbstractImageScorer.score(AbstractImageScorer.java:44)
```

Request:

```
{"query":{
  "image":{
    "cover_image":{
      "feature":"FCTH",
      "image":".........base64........"}
    }
  }
}
```

Mapping:

```
leak_item: {
  properties: {
    artist: {
      type: string
    }
    album: {
      type: string
    }
    cover_fingerprint: {
      type: string
    }
    cover_image: {
      type: string
    }
  }
}
```

**Comment by stephenmuss** [comment]
Shouldn't `cover_image` be of `image` type?

**Comment by such** [comment]
It should indeed! My bad then... Thanks for your help!
